### ISSUE TITLE
Question about 2-dimensional arrays

### ISSUE THREAD

**Issue by WQR53** [resess/ARDiff#1]
Hi, sir

I noticed that the dataset does not contain code for two-dimensional arrays.

Does ARDiff support code equivalence determination for codes that contain 2-dimensional arrays?

Thanks.

**Comment by shrBadihi** [comment]
Hi,

During the development of ARDiff, the underlying model checker we used for symbolic execution in ARDiff could not support 2D arrays properly. 

Bests,
